baseURL: http://examplesite.org
title: Online Learning  platform for Educators
theme: airspace-hugo
paginate: '4'
summaryLength: '30'
disableLanguages: []
disqusShortname: ''
googleAnalytics: ''
outputs:
  home: HTML
markup:
  goldmark:
    renderer:
      unsafe: yes
  tableOfContents:
    endLevel: 1
    ordered: no
    startLevel: 2
params:
  author: KruRoo @ Edu CU
  contact:
    address_descriptors: no
    email: upskill.reskill.educhula@gmail.com
    form:
      action: '#'
      enable: no
      success_image: images/Asset1.svg
      use_netlify: yes
    location: "**คณะครุศาสตร์ จุฬาลงกรณ์มหาวิทยาลัย**  \n 254 ถนนพญาไท  \n แขวงวังใหม่ เขตปทุมวัน  \n กรุงเทพฯ 10330 \n"
  cookies:
    enable: no
    expire_days: 2
  counter:
    enable: no
    username: ''
  description: หลักสูตร ""
  gmap:
    enable: no
    gmap_api: AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU
    map_latitude: '13.7368033'
    map_longitude: '100.5265296'
    map_marker: images/marker.png
  image: images/Asset2.png
  logo: images/Asset2.png
  logo_width: 100px
  plugins:
    css:
      - attributes: media='screen'
        link: plugins/bootstrap/css/bootstrap.min.css
      - attributes: ''
        link: plugins/ionicons/css/ionicons.min.css
      - attributes: ''
        link: plugins/magnific-popup/magnific-popup.min.css
      - attributes: ''
        link: plugins/slick/slick.css
    js:
      - attributes: ''
        link: plugins/jquery/jquery.min.js
      - attributes: ''
        link: plugins/bootstrap/js/bootstrap.min.js
      - attributes: ''
        link: plugins/slick/slick.min.js
      - attributes: ''
        link: plugins/magnific-popup/magnific-popup.min.js
      - attributes: ''
        link: plugins/shuffle/shuffle.min.js
      - attributes: defer
        link: plugins/google-map/gmap.js
  preloader:
    enable: yes
    preloader: ''
  social:
    - icon: ion-social-facebook
      link: 'https://www.facebook.com/Upskill-Reskill-Edu-Chula-108438281469923/'
    - icon: ion-chatbubble-working
      link: 'https://www.facebook.com/messages/t/108438281469923'
    - icon: ion-university
      link: 'www.kruroo.com'
  widgets:
    sidebar:
      - recent_posts
      - taxonomy_category
      - taxonomy_tags
languages:
  en:
    contentDir: content/english
    copyright: Copyright &copy; 2021 [คณะครุศาสตร์ จุฬาลงกรณ์มหาวิทยาลัย](https://www.edu.chula.ac.th/). All Rights
      Reserved.
    languageCode: en-US
    languageName: English
    menu:
      footer:
        - URL: project
          name: รายละเอียดหลักสูตร
          weight: 2
        - URL: service
          name: ความรู้เผยแพร่
          weight: 3
        - URL: faq
          name: FAQ
          weight: 5
        - URL: contact
          name: ติดต่อเรา
          weight: 6
      main:
        - hasChildren: no
          name: More
          weight: 5
    weight: 1
